#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/platform/evmc6678l
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/a0868396/ti/xdctools_3_23_02_47/include/utils.tci:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/include/utils.tci
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/xdc.tci:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/xdc.tci
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/template.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/template.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/om2.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/om2.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/xmlgen.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/xmlgen.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/xmlgen2.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/xmlgen2.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/IPackage.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/IPackage.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/package.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/package.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/services/global/Clock.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/services/global/Clock.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/services/global/Trace.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/services/global/Trace.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/bld.js:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/bld.js
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/BuildEnvironment.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/PackageContents.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/PackageContents.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/_gen.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/_gen.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/Library.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/Library.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/Executable.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/Executable.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/Repository.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/Repository.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/Configuration.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/Configuration.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/Script.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/Script.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/Manifest.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/Manifest.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/Utils.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/Utils.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/ITarget.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/ITarget.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/ITarget2.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/ITarget2.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/ITargetFilter.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/package.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/xdc/bld/package.xs
package.mak: config.bld
/home/a0868396/ti/xdctools_3_23_02_47/packages/ti/targets/ITarget.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/ti/targets/ITarget.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/ti/targets/C28_large.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/ti/targets/C28_large.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/ti/targets/C28_float.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/ti/targets/C28_float.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/ti/targets/package.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/ti/targets/package.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/ti/targets/elf/ITarget.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/ti/targets/elf/ITarget.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/ti/targets/elf/TMS470.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/ti/targets/elf/TMS470.xs
/home/a0868396/ti/xdctools_3_23_02_47/packages/ti/targets/elf/package.xs:
package.mak: /home/a0868396/ti/xdctools_3_23_02_47/packages/ti/targets/elf/package.xs
package.mak: package.bld
endif


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.platform.evmc6678l.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.platform.evmc6678l" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.platform.evmc6678l $@

test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_platform_evmc6678l
ti_platform_evmc6678l.tar: package/package.bld.xml
ti_platform_evmc6678l.tar: package/package.ext.xml
ti_platform_evmc6678l.tar: package/package.rel.dot
ti_platform_evmc6678l.tar: package/build.cfg
ti_platform_evmc6678l.tar: package/package.xdc.inc
ti_platform_evmc6678l.tar: package/package.cfg.xdc.inc
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_platform_evmc6678l.tar.dep
endif
package/rel/ti_platform_evmc6678l/ti/platform/evmc6678l/package/package.rel.xml:

ti_platform_evmc6678l.tar: package/rel/ti_platform_evmc6678l.xdc.inc package/rel/ti_platform_evmc6678l/ti/platform/evmc6678l/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_platform_evmc6678l.xdc.inc,package/rel/ti_platform_evmc6678l.tar.dep)


release release,ti_platform_evmc6678l: all ti_platform_evmc6678l.tar
clean:: .clean
	-$(RM) ti_platform_evmc6678l.tar
	-$(RM) package/rel/ti_platform_evmc6678l.xdc.inc
	-$(RM) package/rel/ti_platform_evmc6678l.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
endif
clean::
	-$(RMDIR) package


